# Generated by Django 5.0.3 on 2024-04-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
